Expose muted channels
GetStream/stream-chat-swift pull request #1011
Opened 2021-04-22 11:05 UTC by evsaev

2021-04-22 21:43 UTC, DominikBucher12 requested changes
Just 2 small improvements and it's good for me.

2021-04-22 21:43 UTC, DominikBucher12 commented on Sources/StreamChat/WebSocketClient/Events/NotificationEvents.swift
> +        guard try response.value(at: \.memberContainer?.invite?.isInvited) == true else {
I just realized that the  payload will never contain `memberContainer`, it's probably safe to delete this code.

2021-04-22 21:43 UTC, DominikBucher12 commented on Tests/StreamChatTests/MockEnpointResponses/CurrentUser.json
> +  "channel_mutes": [
Actually I am missing payload for the whole `NotificationChannelMutesUpdatedEvent` event. I shared to you in internal discussion patch which introduces this JSON + Adds some sample test to it.

2021-04-23 13:01 UTC, VojtaStavik approved these changes

2021-04-23 13:28 UTC, merged