Add UIComponents overview to documentation
GetStream/stream-chat-swift pull request #1191
Opened 2021-06-17 13:23 UTC by DominikBucher12

# What this PR do:
- Adds UIComponents overview to docusaurus, similar to Controllers overview
# How to test it
- Run docusaurus for now, if there will be some iterations, I will fire up the quick look as @nuno-vieira suggested (I need to setup ASAP)

2021-06-17 14:00 UTC, b-onc commented
I can't find the ngrok link 🙃

2021-06-17 14:03 UTC, b-onc requested changes
Is this autogenerated? I was thinking something with more images.. Let's discuss in Slack

2021-06-17 14:03 UTC, b-onc commented on docusaurus/docs/iOS/ui-components/ui-components-overview.md
> +## ChatChannelList
```suggestion
## ChatChannelListVC
```

2021-06-17 14:03 UTC, b-onc commented on docusaurus/docs/iOS/ui-components/ui-components-overview.md
> +A `NavigationRouter` subclass used for navigating from message-list-based view controllers.
Let's move this after Composer

2021-06-18 14:14 UTC, DominikBucher12 reviewed
Added some images, restructured the documentation a bit and tried to give little more overview. Still in draft because I need to finish second half.

2021-07-01 08:24 UTC, closed without merging