CIS-1451 Fix channel message visiblity
GetStream/stream-chat-swift pull request #1730
Opened 2021-12-27 14:57 UTC by tbarbugli

Fixes a regression from the deleted replies fix, the PR adds better tests and cleans up the conditions for showing messages in channels.

2021-12-27 16:36 UTC, polqf approved these changes

2021-12-27 16:36 UTC, polqf commented on Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
> +    func test_channelMessagesPredicate_shouldIncludeDeletedMessages() throws {
Should we also add a test for thread reply being deleted with showReplyInChannel: true?

2021-12-27 16:39 UTC, polqf commented
Also, it is was pointing to develop, but should be pointing to release. Fixed that, but needs a rebase

2021-12-27 16:55 UTC, polqf commented
🐛 GIFs coming from giphy don’t appear in main chat independently of what you select

2021-12-27 16:57 UTC, polqf requested changes
🐛 GIFs coming from giphy don’t appear in main chat independently of what you select

2021-12-27 16:59 UTC, nuno-vieira approved these changes
QA'd, LGTM ✅

2021-12-28 10:06 UTC, polqf commented
Confirmed it is a preexisting issue, we'll move forward

2021-12-28 10:06 UTC, polqf approved these changes

2021-12-28 10:07 UTC, merged