CIS-1457 Handle notification.channel_deleted event
GetStream/stream-chat-swift pull request #1737
Opened 2021-12-28 13:22 UTC by tbarbugli

Handle `notification.channel_deleted` event so that we update the Channel List correctly

2021-12-29 17:08 UTC, polqf commented on Sources/StreamChat/WebSocketClient/Events/NotificationEvents.swift
> +    let createdAt: Date
Is this createdAt property the date in which the channel got deleted? if that's the case, can we document it?

2021-12-29 17:08 UTC, polqf commented on Sources/StreamChat/WebSocketClient/Events/NotificationEvents.swift
> +    let createdAt: Date
Same here

2021-12-29 17:23 UTC, nuno-vieira approved these changes
LGTM! ✅

2021-12-30 12:27 UTC, nuno-vieira requested changes
Requesting changes since I believe we are missing `public` on some props

2021-12-30 12:27 UTC, nuno-vieira commented on Sources/StreamChat/WebSocketClient/Events/NotificationEvents.swift
> +    let createdAt: Date
Shouldn't these properties be public?

2021-12-30 12:33 UTC, merged