Mark SwiftUIRepresentable as Deprecated
GetStream/stream-chat-swift pull request #2129
Opened 2022-06-28 21:37 UTC by adolfogarza

### 🔗 Issue Links

https://stream-io.atlassian.net/browse/CIS-1562

### 🎯 Goal

_Mark SwiftUIRepresentable as Deprecated_

### ☑️ Contributor Checklist
- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] This change follows zero ⚠️ policy (required)
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (docusaurus, tutorial, CMS)

2022-07-04 12:36 UTC, nuno-vieira commented on Sources/StreamChat/Controllers/ChannelController/ChannelController+SwiftUI.swift
> +    @available(*, deprecated, message: "This is now deprecated, please refer to the SwiftUI SDK at https://github.com/GetStream/stream-chat-swiftui")
I don't think we should actually, we have a lot of customers using this and you can always use Combine with UIKit.

2022-07-04 12:39 UTC, martinmitrevski commented on Sources/StreamChat/Controllers/ChannelController/ChannelController+SwiftUI.swift
> +    @available(*, deprecated, message: "This is now deprecated, please refer to the SwiftUI SDK at https://github.com/GetStream/stream-chat-swiftui")
Yes, exactly, that's what I was thinking too.

2022-07-04 15:44 UTC, martinmitrevski reviewed
There are still some places where controllers are unnecessarily deprecated like `ChatUserListController` along with its properties. Basically, in the LLC we shouldn't have any deprecations, only in the UI layer.

Also, I've noticed a lot of new warnings in the UIKit SDK. We need to check those too.

2022-07-05 07:55 UTC, martinmitrevski approved these changes
LGTM ✅

2022-07-05 22:50 UTC, nuno-vieira commented on Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView+SwiftUI.swift
> +    @available(*, deprecated, message: "This is now deprecated, please refer to the SwiftUI SDK at https://github.com/GetStream/stream-chat-swiftui")
The deprecation flags should actually be above the ChatChannelListItemViewSwiftUIView. Any reason why they are on the initialisers?

2022-07-05 22:52 UTC, nuno-vieira requested changes
This should just be a question of Deprecating the SwiftUI Views, making the @available mark above the view types. There's no need to deprecate properties or functional calls

2022-07-06 14:34 UTC, closed without merging