[CIS-550] MessageComposer basic animation
GetStream/stream-chat-swift pull request #703
Opened 2020-12-29 19:10 UTC by mantergo

**In this PR:**

- Update `textColor` with `ColorPalette`
- Fix sendting attachments without text
- Remove left and right extra insets for `MessageComposerView`
- Add basic animation to `MessageComposer`

https://user-images.githubusercontent.com/10098359/103308065-d9912680-4a11-11eb-9fe6-c75591f47073.mp4

2020-12-29 19:24 UTC, VojtaStavik requested changes
Great start. I think it'd be nice if we had just once place where to perform animations so we can control is centrally.

Maybe something like: 
```swift
func WithAnimation(_ actions: () -> Void) {...}
```
Inside this function, we should also check for `UIAccessibilityIsReduceMotionEnabled` value and don't perform animations if it's set.

Finally, let's try to use a spring animation as default. The UI will feel much more snappier.

2020-12-30 12:47 UTC, mantergo commented
> Great start. I think it'd be nice if we had just once place where to perform animations so we can control is centrally.
> 
> Maybe something like:
> 
> ```swift
> func WithAnimation(_ actions: () -> Void) {...}
> ```
> 
> We'd use it as replacement for `UIView.animate { }`. Inside this function, we should also check for `UIAccessibilityIsReduceMotionEnabled` value and don't perform animations if it's set.
> 
> Finally, let's try to use a spring animation as default. The UI will feel much more snappier.

Yeah, good points! Thanks!

2020-12-30 19:14 UTC, VojtaStavik approved these changes

2020-12-30 19:14 UTC, VojtaStavik commented on Sources_v3/StreamChatUI/Utils/Animation.swift
> +func WithAnimation(_ actions: @escaping () -> Void, completion: ((Bool) -> Void)? = nil) {
nit: Are you happy with the name? It seems I don't actually like it 🤦‍♂️ Maybe `Animate { }` would read better on the caller side?

2020-12-30 19:14 UTC, VojtaStavik commented on Sources_v3/StreamChatUI/Utils/Animation.swift
> +    }
nit: `guard` would work much better here

2020-12-31 09:45 UTC, merged